# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.text_box = QtWidgets.QListWidget(self.centralwidget)
        self.text_box.setMaximumSize(QtCore.QSize(16777215, 50))
        self.text_box.setObjectName("text_box")
        self.verticalLayout_3.addWidget(self.text_box)
        self.display_all_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.display_all_checkbox.setObjectName("display_all_checkbox")
        self.verticalLayout_3.addWidget(self.display_all_checkbox)
        self.display_formula_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.display_formula_checkbox.setObjectName("display_formula_checkbox")
        self.verticalLayout_3.addWidget(self.display_formula_checkbox)
        self.Choose_power = QtWidgets.QComboBox(self.centralwidget)
        self.Choose_power.setEnabled(False)
        self.Choose_power.setEditable(True)
        self.Choose_power.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.Choose_power.setObjectName("Choose_power")
        self.verticalLayout_3.addWidget(self.Choose_power)
        self.Open_button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_button.setObjectName("Open_button")
        self.verticalLayout_3.addWidget(self.Open_button)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setObjectName("Save_button")
        self.verticalLayout_3.addWidget(self.Save_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Choose_power.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display_all_checkbox.setText(_translate("MainWindow", "Отобразить графики всех степеней полинома"))
        self.display_formula_checkbox.setText(_translate("MainWindow", "Отобразить формулу полинома"))
        self.Choose_power.setCurrentText(_translate("MainWindow", "Выберите степень полинома"))
        self.Open_button.setText(_translate("MainWindow", "Выбрать файл с входными данными"))
        self.Save_button.setText(_translate("MainWindow", "Сохранить результаты"))
