# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_with_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.Text_box = QtWidgets.QListWidget(self.centralwidget)
        self.Text_box.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Text_box.setObjectName("Text_box")
        self.verticalLayout_3.addWidget(self.Text_box)
        self.Display_formula_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Display_formula_checkbox.setEnabled(False)
        self.Display_formula_checkbox.setObjectName("Display_formula_checkbox")
        self.verticalLayout_3.addWidget(self.Display_formula_checkbox)
        self.PowerTable = QtWidgets.QTableWidget(self.centralwidget)
        self.PowerTable.setEnabled(False)
        self.PowerTable.setMaximumSize(QtCore.QSize(16777215, 150))
        self.PowerTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.PowerTable.setRowCount(8)
        self.PowerTable.setColumnCount(1)
        self.PowerTable.setObjectName("PowerTable")
        self.PowerTable.horizontalHeader().setVisible(True)
        self.PowerTable.horizontalHeader().setDefaultSectionSize(1000)
        self.PowerTable.horizontalHeader().setHighlightSections(True)
        self.PowerTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.PowerTable)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.Open_button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_button.setObjectName("Open_button")
        self.verticalLayout_3.addWidget(self.Open_button)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setEnabled(False)
        self.Save_button.setObjectName("Save_button")
        self.verticalLayout_3.addWidget(self.Save_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Display_formula_checkbox.setText(_translate("MainWindow", "Отобразить формулу полинома"))
        self.label.setText(_translate("MainWindow", "Вы можете выбирать несколько степеней полинома при помощи клавиши CTRL, а также выбрать диапазон при помощи клавиши SHIFT"))
        self.Open_button.setText(_translate("MainWindow", "Выбрать файл с входными данными"))
        self.Save_button.setText(_translate("MainWindow", "Сохранить результаты"))
