# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 600))
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.Text_box = QtWidgets.QListWidget(self.centralwidget)
        self.Text_box.setMinimumSize(QtCore.QSize(0, 50))
        self.Text_box.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Text_box.setObjectName("Text_box")
        self.verticalLayout_3.addWidget(self.Text_box)
        self.Display_formula_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Display_formula_checkbox.setEnabled(False)
        self.Display_formula_checkbox.setObjectName("Display_formula_checkbox")
        self.verticalLayout_3.addWidget(self.Display_formula_checkbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PowerTable = QtWidgets.QTableWidget(self.centralwidget)
        self.PowerTable.setEnabled(False)
        self.PowerTable.setMinimumSize(QtCore.QSize(890, 0))
        self.PowerTable.setMaximumSize(QtCore.QSize(16777215, 150))
        self.PowerTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.PowerTable.setRowCount(8)
        self.PowerTable.setColumnCount(1)
        self.PowerTable.setObjectName("PowerTable")
        self.PowerTable.horizontalHeader().setVisible(False)
        self.PowerTable.horizontalHeader().setDefaultSectionSize(1000)
        self.PowerTable.horizontalHeader().setHighlightSections(True)
        self.PowerTable.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.PowerTable)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.Number_of_points = QtWidgets.QLineEdit(self.centralwidget)
        self.Number_of_points.setEnabled(False)
        self.Number_of_points.setMaximumSize(QtCore.QSize(190, 150))
        self.Number_of_points.setMaxLength(3)
        self.Number_of_points.setObjectName("Number_of_points")
        self.verticalLayout_4.addWidget(self.Number_of_points)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.Open_button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_button.setObjectName("Open_button")
        self.verticalLayout_3.addWidget(self.Open_button)
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setEnabled(False)
        self.Save_button.setObjectName("Save_button")
        self.verticalLayout_3.addWidget(self.Save_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuAuthor = QtWidgets.QMenu(self.menuBar)
        self.menuAuthor.setObjectName("menuAuthor")
        MainWindow.setMenuBar(self.menuBar)
        self.Author = QtWidgets.QAction(MainWindow)
        self.Author.setObjectName("Author")
        self.menuAuthor.addAction(self.Author)
        self.menuBar.addAction(self.menuAuthor.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Display_formula_checkbox.setText(_translate("MainWindow", "Отобразить формулу полинома"))
        self.label_2.setText(_translate("MainWindow", "Количество \n"
"точек \n"
"полинома:"))
        self.label.setText(_translate("MainWindow", "Вы можете выбирать несколько степеней полинома при помощи клавиши CTRL, а также выбрать диапазон при помощи клавиши SHIFT"))
        self.Open_button.setText(_translate("MainWindow", "Выбрать файл с входными данными"))
        self.Save_button.setText(_translate("MainWindow", "Сохранить результаты"))
        self.menuAuthor.setTitle(_translate("MainWindow", "About"))
        self.Author.setText(_translate("MainWindow", "Author"))
