# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_warning_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 300)
        Dialog.setMinimumSize(QtCore.QSize(380, 300))
        Dialog.setMaximumSize(QtCore.QSize(380, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.warning_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.warning_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.warning_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.warning_buttonBox.setCenterButtons(True)
        self.warning_buttonBox.setObjectName("warning_buttonBox")
        self.verticalLayout.addWidget(self.warning_buttonBox)

        self.retranslateUi(Dialog)
        self.warning_buttonBox.accepted.connect(Dialog.accept)
        self.warning_buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Внимание! "))
        self.label_15.setText(_translate("Dialog", "Внимание! Правильное редактирование данных (очистка от выбросов, удаление некооректных значений и др.) может в несколько раз повысить предсказательную силу и точность модели, однако данный инструментарий предоставляется для продвинутого пользователя. В случае, если вы не уверены, что способны обработать данные корректно или чувствуете, что нуждаетесь в помощи обратитесь к поставщику программного обеспечения для получения соответствующей услуги. "))
        self.label.setText(_translate("Dialog", "Нажмите ОК, для продолжения или Cancel чтобы вернуться назад"))
